#!/bin/bash

export DISPLAY=:0

baseDir="$HOME/.config/lbrss"

feedsDir="$baseDir/feeds"

function filter_html {
	[ ! -f "$1" ] && return
	cat "$1" | xmlstarlet unesc | sponge "$1"
}

[ ! -d "$feedsDir" ] && mkdir -p "$feedsDir"

grep -v "^#" "$baseDir"/urls | while read -r url; do
	name=$(cut -f 1 <<< "$url")
	url=$(cut -f 2 <<< "$url")

	orig_file="$feedsDir/${name}.xml"
	[ ! -f "$orig_file" ] && wget --quiet "$url" -O "$orig_file" &&
		echo "New feed: $name" && filter_html "$orig_file" && continue

	new_file="$feedsDir/${name}_new.xml"
	wget --quiet "$url" -O "$new_file"

	filter_html "$new_file"

	new_films=$(comm -13 <(sort "$orig_file") <(sort "$new_file"))

	[ -z "$new_films" ] || [ "$(echo "$new_films" | wc -l)" == 0 ] && echo "No new movies for $name" &&
		rm "$new_file" && continue

	new_films=$(xmlstarlet unesc <<< "$new_films")
	films=$(grep "<item>.*letterboxd:watchedDate.*</item>" <<< "$new_films")

	echo "$films" | while read -r film; do
		title=$(grep -Po "(?<=<letterboxd:filmTitle>).*(?=</letterboxd:filmTitle>)" <<< "$film")
		year=$(grep -Po "(?<=<letterboxd:filmYear>).*(?=</letterboxd:filmYear>)" <<< "$film")
		# optionally add watched date as well
		#watchedDate=$(echo "$film" | grep -Po "(?<=<letterboxd:watchedDate>).*(?=</letterboxd:watchedDate>)")

		re=""
		[ "$(grep "<letterboxd:rewatch>Yes</letterboxd:rewatch>" <<< "$film")" ] && re="re"

		reviewText=""
		[ "$(grep "letterboxd-review" <<< "$film")" ] && reviewText="reviewed"

		ratingText=""
		rating=$(grep -Po "(?<=<letterboxd:memberRating>).*(?=</letterboxd:memberRating>)" <<< "$film")
		[ "$rating" ] && ratingText=" and rated" && rating+=" stars"


		if [ "$reviewText" ] && [ "$ratingText" ]; then
			reviewText=", $reviewText"
		elif [ "$reviewText" ]; then
			reviewText=" and $reviewText"
		fi

		link=$(grep -Po "(?<=<link>).*(?=</link>)" <<< "$film")

		# format for links in notifications
		# <a href=\"https://forums.bunsenlabs.org/\">BL</a>
		notify-send --icon "$baseDir/lb.png" "lbrss" "<a href=\"$link\">$name ${re}watched${reviewText}${ratingText} $title ($year) $rating</a>"

		# optional system beep
		# first enable kernel module https://askubuntu.com/a/19909/629804
		beep
	done

	mv "$new_file" "$orig_file"

done
